-- MySQL Script generated by MySQL Workbench
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering
-- https://docs.oracle.com/cd/E19078-01/mysql/mysql-workbench/workbench-faq.html#:~:text=SET%20%40OLD_SQL_MODE%3D%40%40SQL_MODE%2C%20SQL_MODE%3D%27TRADITIONAL%27%3B%3A%20Sets%20SQL_MODE%20to%20TRADITIONAL%2C%20causing,end%20of%20the%20script%20using%20the%20following%20statements%3A
-- SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
-- SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

DROP TABLE IF EXISTS `anecdote_category` ;
DROP TABLE IF EXISTS `anecdote_action` ;
DROP TABLE IF EXISTS `category` ;
DROP TABLE IF EXISTS `anecdote` ;
DROP TABLE IF EXISTS `user` ;

-- -----------------------------------------------------
-- Table `user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `user` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`pseudo` VARCHAR(30) NOT NULL, 
`email` VARCHAR(255) NOT NULL,
`password` VARCHAR(64) NOT NULL,
`img` VARCHAR(255) DEFAULT NULL, 
`roles` TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '1 => user, 2 => admin',
`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
`updated_at` DATETIME DEFAULT NULL,
`is_verified` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '0 => email not verified, 1 => email verified',
PRIMARY KEY (`id`),
UNIQUE INDEX (`pseudo`, `email`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `category`
-- -----------------------------------------------------

CREATE TABLE `category` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,  
`name` VARCHAR(255) NOT NULL, 
`color` VARCHAR(255) DEFAULT NULL, 
`img` VARCHAR(255) NULL,  
`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
`updated_at` DATETIME DEFAULT NULL,
`slug` VARCHAR(255) NOT NULL,
PRIMARY KEY (`id`) )
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `anecdote`
-- -----------------------------------------------------
CREATE TABLE `anecdote` (
`id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
`title` VARCHAR(255) NOT NULL, 
`description` VARCHAR(255) DEFAULT NULL, 
`content` VARCHAR(10000) NOT NULL, 
`img` VARCHAR(255) DEFAULT NULL, 
`source` VARCHAR(255) DEFAULT NULL, 
`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
`updated_at` DATETIME DEFAULT NULL,
`writer_id` INT UNSIGNED DEFAULT 1,
`category_1` INT UNSIGNED DEFAULT NULL,
`category_2` INT UNSIGNED DEFAULT NULL,
`category_3` INT UNSIGNED DEFAULT NULL,

PRIMARY KEY (`id`),
INDEX `fk_writer_id` (`writer_id`),
FOREIGN KEY (`writer_id`) REFERENCES `user`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,

INDEX `fk_anecdote_category_1` (`category_1`),
FOREIGN KEY (`category_1`) REFERENCES `category`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,

INDEX `fk_anecdote_category_2` (`category_2`),
FOREIGN KEY (`category_2`) REFERENCES `category`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,

INDEX `fk_anecdote_category_3` (`category_3`),
FOREIGN KEY (`category_3`) REFERENCES `category`(`id`) ON DELETE SET NULL ON UPDATE CASCADE)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `anecdote_action`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `anecdote_action` (
`vote` TINYINT(1) UNSIGNED NOT NULL DEFAULT 0 COMMENT '0 =>no vote, 1 => upVote, 2 => downVote',
`favorite` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 => false, 1 => true',
`anecdote_id` INT UNSIGNED NOT NULL, 
`user_id` INT UNSIGNED NOT NULL, 
PRIMARY KEY (`anecdote_id`, `user_id`),
INDEX `fk_anecdote_id` (`anecdote_id`),
FOREIGN KEY (`anecdote_id`) REFERENCES `anecdote`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (`user_id`) REFERENCES `user`(`id`) ON DELETE CASCADE ON UPDATE CASCADE)
ENGINE = InnoDB;

-- SET SQL_MODE=@OLD_SQL_MODE; 
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS; 
-- SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
