-- -----------------------------------------------------
-- Data for table `anecdote`
-- -----------------------------------------------------
INSERT INTO `anecdote` (`id`,`title`, `description`, `content`, `img`, `source`, `created_at`, `updated_at`, `writer_id`, `category_1`, `category_2`, `category_3`) VALUES (1, "La banane VS l’être humain", 'La taille ne fait pas tout !', 'Aussi incroyable que cela puisse paraître, les hommes comptent 23 000 gènes, contre 36 000 pour la banane. Ce fruit exotique a en effet subi de nombreuses mutations génétiques et croisements entre espèces sous la main de l’Homme. La banane étant le fruit le plus populaire dans les pays industrialisés. La banana a donc plus de gènes que l’être humain.', DEFAULT, 'https://dailygeekshow.com/plantes-nature-arbres/', DEFAULT, DEFAULT, 1, 1, DEFAULT, DEFAULT),
(2, 'La plus grande fleur du monde', 'Et non, ce n’est pas un pokémon !', 'Cette fleur que l’on peut trouver en Asie-Pacifique peut mesurer jusqu’à 1 mètre de diamètre et peser 10 kilos, l’équivalent d’un enfant de 1 an ! La Rafflesia est la plus grande fleur du monde. Autre fait insolite, elle attire les mouches qui assurent sa pollinisation en dégageant une odeur de viande en décomposition.', DEFAULT, 'https://dailygeekshow.com/plantes-nature-arbres/', DEFAULT, DEFAULT, 1, 1, DEFAULT, DEFAULT),
(3, 'Le mimosa est intimidable', 'Les plantes sont des être vivants en mouvements', 'Cette plante étonnante porte bien son nom. Au moindre contact, ses feuilles se replient. Une sensibilité incroyable qui lui a d’ailleurs donné son surnom de “sensitive”. On peut trouver le mimosa pudica en Amérique du Sud ainsi qu’en Asie du Sud-Est.', DEFAULT, 'https://dailygeekshow.com/plantes-nature-arbres/', DEFAULT, DEFAULT, 1, 1, DEFAULT, DEFAULT),
(4, 'Les cactus dans le monde', 'les diners de famille doivent donner du piquant', 'Il existe plus de 2000 espèces de cactus dans le monde. Les cactus peuvent présenter des caractéristiques très différentes selon les espèces. Ainsi, le petit ne mesure que 1,3 centimètre, alors que le plus gros peut atteindre 19 mètres de hauteur. Malheureusement, 31 % des 2 000 espèces existantes de cactus, soit environ 500, sont en voie de disparition, notamment à cause de l’agriculture.', DEFAULT, 'https://dailygeekshow.com/plantes-nature-arbres/', DEFAULT, DEFAULT, 1, 1, DEFAULT, DEFAULT),
(5, 'Le philosophe pervers', 'c’est qu’il en avait dans le pantalon le philosophe !', 'Le mot orchidée tire son nom du mot grec “orchis”, qui veut dire testicule. Drôle d’appellation pour une plante… On l’attribue à Théophraste, un philosophe de la Grèce antique. Cette dénomination fait référence aux tubercules souterrains que possèdent certaines orchidées, qui ressemblent étrangement aux parties génitales masculines.', DEFAULT, 'https://dailygeekshow.com/plantes-nature-arbres/', DEFAULT, DEFAULT, 1, 1, DEFAULT, DEFAULT),
(6, 'Un guitariste astrophysicien', DEFAULT, 'Brian May, guitariste de génie du groupe Queen, a un talent qui dépasse les frontières de la scène. Il est également docteur en astrophysique depuis 2007 et est co-créateur d’un stéréoscope. Il a également construit sa propre guitare électrique, la Red Special, avec des pièces de machines à laver.', DEFAULT, 'https://www.jamzone.com/fr/blog/724-20-anecdotes-insoupconnees-sur-la-musique-premiere-partie.html', DEFAULT, DEFAULT, 1, 2, DEFAULT, DEFAULT),
(7, 'Personne ne bat Jimi', DEFAULT, "Lors d'un concert à Londres en 1966, Jimi Hendrix monta sur scène pour jouer avec Eric Clapton, à l'époque surnommé « Dieu » pour ses talents de guitariste. Le fougueux Jimi Hendrix se mit à jouer « Killin’ Floor » de Howlin Wolf avec les dents puis en mettant sa guitare derrière sa tête. Clapton fut tellement dévasté de la performance qu'il quitta la scène et rentra en taxi, pensant que sa carrière était finie. Heureusement les deux génies ont réussi à cohabiter encore de nombreuses années !", DEFAULT, 'https://www.jamzone.com/fr/blog/724-20-anecdotes-insoupconnees-sur-la-musique-premiere-partie.html', DEFAULT, DEFAULT, 1, 2, DEFAULT, DEFAULT),
(8, '144 fois', 'Et pas une de plus !', "C’est le nombre de fois qu’est répété “around the world” dans le titre du même nom du groupe français Daft Punk.", DEFAULT, 'https://www.jamzone.com/fr/blog/724-20-anecdotes-insoupconnees-sur-la-musique-premiere-partie.html', DEFAULT, DEFAULT, 1, 2, DEFAULT, DEFAULT),
(9, 'Le cochon volant de Pink Floyd', DEFAULT, "Algie est le nom donné à un cochon géant gonflé à l'hélium censé être utilisé pour la pochette de l'album « Animals » de Pink Floyd. En effet, l'idée était de le faire flotter au dessus de Battersea (la centrale électrique londonienne que l'on voit sur la pochette) et de le prendre en photo. Une malheureuse rafale de vent à libéré la bête. Durant son périple, il bloqua l’aéroport de Londres-Heathrow, car il volait au milieu des couloirs aériens. Il fut finalement retrouvé écrasé dans une ferme du Kent.", DEFAULT, 'https://www.jamzone.com/fr/blog/724-20-anecdotes-insoupconnees-sur-la-musique-premiere-partie.html', DEFAULT, DEFAULT, 1, 2, DEFAULT, DEFAULT),
(10, 'beyoncé doublée par un vieillard','C’est pas au vieux singes que l’on apprends à faire la grimace', "Mozart a vendu plus de CDs en 2016 que Beyoncé.", DEFAULT, 'https://www.version-karaoke.fr/blog/639-15-anecdotes-sur-la-musique-qui-pourraient-vous-surprendre.html', DEFAULT, DEFAULT, 1, 2, DEFAULT, DEFAULT),
(11, 'Quand l’arbitre a vu rouge', DEFAULT, "On doit le carton, dans le monde du football à un Anglais : Ken Aston.
Cet arbitre assiste au match Angleterre-Argentine durant la Coupe du monde 1966. A cette époque, rien ne matérialise les sanctions : l'avertissement et l'expulsion se font de manière verbale.
Durant la rencontre, un joueur argentin est expulsé par l'arbitre mais il refuse de sortir. Depuis les tribunes, Ken Aston est écœuré par la réaction de l'Argentin.
Sur le chemin du retour, il s'arrête en voiture à un feu de circulation. Et là, eureka ! En voyant le feu jaune, qui signale 'attention', puis le feu rouge lui signifiant 'stop', il se dit que le code est adaptable au football. Un carton jaune servira à avertir un joueur, un rouge à l'exclure.
Son idée séduit la FIFA, qui l'adopte lors de la Coupe du monde 1970. Le dimanche 31 mai 1970, l'arbitre allemand Kurt Tschenscher octroie à Evgeni Lovchev, le n°6 de l'équipe soviétique, le 1er carton jaune de l'histoire de la Coupe du monde de football, lors du match de poule Mexique-Union Soviétique (0-0).
", DEFAULT, 'https://www.yabiladi.com/forum/insolites-anecdotes-sport-51-2547139.html', DEFAULT, DEFAULT, 1, 3, DEFAULT, DEFAULT),
(12, 'le meilleur buteur de Montpellier', DEFAULT, "Laurent Blanc est le meilleur buteur de l’histoire de Montpellier. Évoluant pendant la quasi-totalité de sa carrière en tant que défenseur, Laurent Blanc est le meilleur buteur de l'histoire de Montpellier.", DEFAULT, 'https://www.pkfoot.com/histoire/top-anecdotes', DEFAULT, DEFAULT, 1, 3, DEFAULT, DEFAULT),
(13, 'Et un, et deux… Et 149-0', DEFAULT, "En 2002, une équipe malgache, mécontente du traitement arbitral infligé à son entraîneur, décide de fausser un résultat. Bilan : une défaite 149-0. Et surtout 149 buts contre leur camp des joueurs de l'Es Emryne offerts à leurs adversaires de l'AS Adema. Auparavant, le record de buts marqués contre son camp état détenu par Catane qui avait involontairement marqué quatre fois dans ses propres filets face à l'Inter Milan lors de la saison 1960-61.", DEFAULT, 'https://fr.news.yahoo.com/ces-anecdotes-qui-ont-marqu%C3%A9-le-foot-134824623.html', DEFAULT, DEFAULT, 1, 3, DEFAULT, DEFAULT),
(14, 'Arrêté sur le terrain... ', DEFAULT, "En 1978, en Tanzanie, l'arbitre du match avait de bonnes raisons de ne pas siffler comme il le fallait. Il avait tellement fumé de marijuana avant la rencontre qu'il était à côté de la plaque et a même dû être arrêté sur la pelouse sans passer par la case contrôle antidopage.", DEFAULT, 'https://fr.news.yahoo.com/ces-anecdotes-qui-ont-marqu%C3%A9-le-foot-134824623.html', DEFAULT, DEFAULT, 1, 3, DEFAULT, DEFAULT),
(15, 'A la maternité puis le triplé', DEFAULT, "Membre du Red Bull Salzbourg, Jonathan Soriano est arrivé en retard pour la rencontre de son équipe face au Wolfsberger AC. Il avait obtenu l'autorisation d'aller assister à la naissance de son troisième enfant mais son club avait pris le pari de l'inscrire quand même sur la feuille de match. Au cas où il pourrait rentrer à temps… Ce fut le cas : revenu à la mi-temps, le papa entre en jeu et plante un hat-trick épatant en 45 minutes. Son équipe s'impose 6-2 et le joueur peut dédier son triplé à sa fille née ce 20 avril 2013.", DEFAULT, 'https://fr.news.yahoo.com/ces-anecdotes-qui-ont-marqu%C3%A9-le-foot-134824623.html', DEFAULT, DEFAULT, 1, 3, DEFAULT, DEFAULT),
(16, "Les loutres sont les animaux les plus mignons", DEFAULT, "Les loutres se tiennent la main lorsqu'elles dorment pour ne pas être emportées par le courant. De même, les loutres de mer forment «des radeaux» lorsqu'elle dorment en se tenant les unes autres autres. Le plus grand radeau jamais vu contenait 2 000 loutres. Et elles disposent aussi d'une poche spéciale sous leur aisselle où elles peuvent transporter des cailloux qu'elles utilisent pour ouvrir les coquillages.", DEFAULT, 'https://www.buzzfeed.com/fr/jemimaskelley/22-anecdotes-sur-les-animaux-qui-vont-vous-donner-envie-de', DEFAULT, DEFAULT, 1, 4, DEFAULT, DEFAULT),
(17, "Les ornithorynques a des super pouvoirs", DEFAULT, "Les ornithorynques nagent les yeux fermés. Lorsque l'ornithorynque nage, il ouvre ses narines et ferme ses yeux et ses oreilles situés dans une rainure juste à l'arrière de son bec. En plus d'être aveugle sous l'eau, il est aussi sourd et se guide grâce à sa mâchoire gris-bleu qui ressemble à un bec et est avant tout un organe sensoriel !", DEFAULT, 'https://hitek.fr/bonasavoir/faits-insolites-animaux_962', DEFAULT, DEFAULT, 1, 4, DEFAULT, DEFAULT),
(18, "Le rire n'est pas que humain", DEFAULT, "Les rats rient lorsqu’ils sont chatouillés. Pour aboutir à ce résultat, les scientifiques se sont référés à une découverte des années 2000 qu’ils ont confirmée… en chatouillant des rats. Plus précisément, ils ont démontré que lorsque les animaux sont chatouillés, ils émettent des vocalises à une fréquence de 50 kHz, soit un véritable signe de plaisir. Leur activité neuronale confirme l’hypothèse du rire chez le rat : lorsqu’un individu est chatouillé sur le ventre et le dos, son excitation neuronale est bien plus importante que lorsqu’il est seulement caressé. En revanche, lorsque le rat est stressé, il ne rit plus du tout…", DEFAULT, 'https://wamiz.com/rongeurs/actu/rats-rient-meme-chatouilleux-8975.html', DEFAULT, DEFAULT, 1, 4, DEFAULT, DEFAULT),
(19, "Michel-Ange et la Sixtine", DEFAULT, "Michel-Ange, appelé à Rome pour peindre le plafond de la chapelle Sixtine, mit quatre ans à réaliser cette oeuvr. Allongé sur un echaffaudage, il peignait étendu, le pinceau about de bras, la peinture coulant sur son visage, en rempant pour avancer et en se cotorisant pour éviter d'ôter la peinture non sèche. Quand le pape venait le houspiller pour aller plus vite, Michel-ange n'hésitait pas à lui faire tomber des pot de peinture sur la tête !", DEFAULT, 'https://www.histoire-pour-tous.fr/anecdotes.html', DEFAULT, DEFAULT, 1, 5, DEFAULT, DEFAULT),
(20, "Le parodie dramatique du film là-haut", DEFAULT, "Aux États-Unis, en 1986, deux personnes ont trouvé la mort en raison de plus d'un million de ballons lâchés dans les airs. Battre ce record du monde pouvait avoir l'air amusant. Mais la «Balloonfest» de Cleveland, dans l'Ohio, s'est avérée mortelle. Les innombrables ballons ont rempli les airs, ce qui a pratiquement aveuglé les pilotes d'avion passant par là. Certaines des baudruches sont ensuite tombées sur le lac Érié, empêchant l'hélicoptère des gardes-côtes de rejoindre deux personnes qui se noyaient.", DEFAULT, 'https://www.buzzfeed.com/fr/michellerennex/18-anecdotes-historiques-qui-ont-lair-fausses-et-qui-sont', DEFAULT, DEFAULT, 1, 5, DEFAULT, DEFAULT),
(21, "L'armée américaine et batman", DEFAULT, "Pendant la seconde guerre mondiale, l'armée américaine a envisagé d'utiliser des chauves-souris... . La bombe à chauves-souris a été conçue par le Dr Lytle Adams. L'idée paraît folle: les chauves-souris armées de bombes incendiaires, auraient été placées dans une bombe plus grande qui aurait explosé au milieu des airs, dispersant les animaux et leur charge explosive dans les villes. Deux millions de dollars ont été dépensés pour mener une trentaine de tests, mais le procédé n'a jamais été employé contre les villes japonaises.", DEFAULT, 'https://www.buzzfeed.com/fr/michellerennex/18-anecdotes-historiques-qui-ont-lair-fausses-et-qui-sont', DEFAULT, DEFAULT, 1, 5, DEFAULT, DEFAULT),
(22, "Un sourire d'enfer", DEFAULT, "Au XVIIIe et XIXe siècle, des prothèses dentaires étaient conçues à partir des dents de soldats décédés. Les prothèses dentaires étaient le plus souvent en ivoire. Mais ces dernières ne paraissaient pas naturelles, elles étaient chères, et elles étaient susceptibles de se briser plus rapidement. Des opportunistes ont donc collecté les dents frontales intactes de la bouche des soldats morts sur le champ de bataille de Waterloo. Les prothèses furent ainsi baptisées «dents de Waterloo».", DEFAULT, 'https://www.buzzfeed.com/fr/michellerennex/18-anecdotes-historiques-qui-ont-lair-fausses-et-qui-sont', DEFAULT, DEFAULT, 1, 5, DEFAULT, DEFAULT),
(23, "Babar la seule victime", DEFAULT, "La première bombe lâchée par les alliés au dessus de Berlin pendant la Seconde Guerre mondiale a tué l'unique éléphant du zoo de la ville.", DEFAULT, 'https://hitek.fr/actualite/top-30-fait-historique-surprenants_2553', DEFAULT, DEFAULT, 1, 5, DEFAULT, DEFAULT),
(24, "La guerre la plus courte", DEFAULT, "38 minutes ! C'est le temps de conflit entre l'Angleterre et le Zanzibar en 1896, c'est ce qu'on peut appeler une guerre éclair.", DEFAULT, 'https://hitek.fr/actualite/top-30-fait-historique-surprenants_2553', DEFAULT, DEFAULT, 1, 5, DEFAULT, DEFAULT),
(25, "La Xbox viens de l'espace", DEFAULT, "La Xbox originale contenait des extraits sonores de vraies missions spatiales. La Xbox originale contenait des extraits sonores édités de transmissions réelles des missions Apollo.
Si vous avez laissé la Xbox sur l’écran d’accueil, vous finirez par entendre des chuchotements de conversation de véritables bavardages de la mission Apollo", DEFAULT, 'https://www.boutique-box-internet.fr/200-anecdotes-tech-pour-briller-en-societe/', DEFAULT, DEFAULT, 1, 6, DEFAULT, DEFAULT),
(26, "Minecraft, le plus grand terrain de jeu", DEFAULT, "le jeu Minecraft (jeu de construction et d’aventure  dans un monde ouvert) offre aujourd’hui une surface de jeu quasi infinie. Seul une limite technique bloque les joueurs 4 milliards de mètres carrés…. soit 8 fois la surface de la Terre, il y a donc le temps avant d’arriver à la fin du jeu !", DEFAULT, 'https://quartierdudigital.fr/6-anecdotes-incroyable-sur-les-jeux-videos/', DEFAULT, DEFAULT, 1, 6, DEFAULT, DEFAULT),
(27, "Tetris victime de son succès", DEFAULT, "Tetris est le premier jeu piraté de l’Histoire. Bien avant l’arrivée de la PlayStation et des premiers jeux piratés, Tetris fut le premier jeu à circuler illégalement. Quand Alekseï Pajitnov l’a imaginé en 1984, il l’a créé sans déposer les droits de création. Dans les années qui ont suivi sa création, il a essayé de vendre le jeu, sans grand succès. Ses amis ont alors commencé à distribuer le jeu à leurs amis qui l’ont à leur tour donné à des amis. La popularité du jeu a grandi ainsi, jusqu’à devenir officiellement édité. Tetris est donc le premier jeu à avoir été obtenu sans être payé.", DEFAULT, 'https://dailygeekshow.com/9-anecdotes-tetris/', DEFAULT, DEFAULT, 1, 6, DEFAULT, DEFAULT),
(28, "Nintendo a commencé petit", DEFAULT, "Nintendo vendait des jeux de cartes à l’origine. Bien évidemment, les consoles n’existaient pas en 1889 lors de la création de Nintendo. Il s’agissait à l’origine d’une société spécialisée dans les cartes à jouer. Dans les années 1960, la compagnie s’est ensuite lancée dans plusieurs secteurs différents, avec notamment des taxis et du riz à cuisson instantanée (oui, vous avez bien lu). Ce n’est qu’en 1972 que Nintendo met un premier pied dans l’univers du jeu vidéo.", DEFAULT, 'https://www.ouest-france.fr/high-tech/jeux-video/jeux-video-dix-anecdotes-qui-vous-feront-voir-nintendo-autrement-7116809', DEFAULT, DEFAULT, 1, 6, DEFAULT, DEFAULT),
(29, "Pourquoi les Chomps aboient ?", DEFAULT, "Petite frayeur de jeunesse, les Chain Chomps ont fait quelques apparitions marquantes sur ce classique qu’est Super Mario 64. L’idée de les attacher à une chaîne, et de les faire aboyer vient de sensei Miyamoto lui-même. En effet, enfant, le développeur fut poursuivi par un chien qui essaya de le mordre mais il se trouva sauvé par la chaîne du molosse qui le stoppa net. C’est donc tout naturellement qu’il transposa cette expérience de jeunesse en cet ennemi bien connu de Mario.", DEFAULT, 'https://new-game-plus.fr/5-anecdotes-facts-super-mario-64/', DEFAULT, DEFAULT, 1, 6, DEFAULT, DEFAULT),
(30, "Le mot de passe de la mort", DEFAULT, "Le mot de passe des ordinateurs chargés de contrôler les missiles nucléaires de l’armée américaine pendant des années était 00000000. Et aussi, au cas où quelqu’un l’oublierait, certains soldats le recevaient écrit sur papier. En résumé, nous sommes miraculeusement vivants.", DEFAULT, 'https://pandorafms.com/blog/fr/anecdotes-informatiques/', DEFAULT, DEFAULT, 1, 7, DEFAULT, DEFAULT),
(31, "Drôle de virus", DEFAULT, "Chaque mois, plus de 6 000 nouveaux virus informatiques sont créés. Dans ce qui semble être une course vorace pour être plus nombreux que les virus biologiques. Il s’agit d’une race douteuse, au fait.", DEFAULT, 'https://pandorafms.com/blog/fr/anecdotes-informatiques/', DEFAULT, DEFAULT, 1, 7, DEFAULT, DEFAULT),
(32, "Le logo de Firefox, tu croyais savoir ?", DEFAULT, "Le logo Firefox n’est pas un renard. On croit souvent à tort que le logo doit être un renard parce que le navigateur s’appelle Firefox. Étonnamment, la mignonne créature à fourrure du logo est en fait un panda rouge !
", DEFAULT, 'https://www.boutique-box-internet.fr/200-anecdotes-tech-pour-briller-en-societe/', DEFAULT, DEFAULT, 1, 7, DEFAULT, DEFAULT),
(33, "iTunes a des conditions générales de vente inhabituelles", DEFAULT, "En acceptant les conditions générales d’iTunes, vous vous engagez à ne pas l’utiliser pour fabriquer des armes nucléaires.
La clause stipule : “Vous acceptez également de ne pas utiliser ces produits pour…. le développement, la conception, la fabrication ou la production d’armes nucléaires, de missiles ou d’armes chimiques ou biologiques”.
", DEFAULT, 'https://www.boutique-box-internet.fr/200-anecdotes-tech-pour-briller-en-societe/', DEFAULT, DEFAULT, 1, 7, DEFAULT, DEFAULT),
(34, "La garantie stricte de Apple", DEFAULT, "Fumer annulera la garantie Apple. Apple a interdit de “fumer” sur ses ordinateurs, ce qui signifie que si vous fumez en utilisant un ordinateur Apple, la garantie devient nulle et non avenue.”.
", DEFAULT, 'https://www.boutique-box-internet.fr/200-anecdotes-tech-pour-briller-en-societe/', DEFAULT, DEFAULT, 1, 7, DEFAULT, DEFAULT),
(35, "L'ensemble de l'humanité mesurée entre la Suisse et la France", DEFAULT, "L’ensemble de l’Humanité rentrerait dans le lac Léman. Si on empilait les 7 milliards d’humains les uns sur les autres (genre lors d’une grosse soirée), on formerait un cube de 2,3 km³. Ce qui remplirait entièrement le lac Léman. Pensez à vos brassards.", DEFAULT, 'https://www.topito.com/top-anecdote-scientifique-bac-s', DEFAULT, DEFAULT, 1, 8, DEFAULT, DEFAULT),
(36, "Nous buvons tous de l’urine de dinosaure", DEFAULT, "La surface de la Terre est recouverte à 71% d’eau, soit 1,36 milliard de km3. Et la Terre ne crée aucune nouvelle quantité d’eau. Tout est recyclé. TOUT. Les dinosaures ont vécu 165 millions d’années, donc ils ont bien eu le temps de pisser dans la flotte. Donc, l’eau que tu vois est forcément passée par la vessie d’un T-Rex.", DEFAULT, 'https://www.topito.com/top-anecdote-scientifique-bac-s', DEFAULT, DEFAULT, 1, 8, DEFAULT, DEFAULT),
(37, "On peut se souvenir de sa naissance", DEFAULT, "Alors toi non. Mais certains l’ont fait. Genre Ray Bradbury, le mec qui a écrit Fahrenheit 415 et les Chroniques martiennes. Ils se souvenaient de sa naissance et de ses cauchemars lors de ses premiers jours. Mais globalement, on oublie sa naissance, car elle est traumatisante. Tu sors du sexe de ta mère quand même.", DEFAULT, 'https://www.topito.com/top-anecdote-scientifique-bac-s', DEFAULT, DEFAULT, 1, 8, DEFAULT, DEFAULT),
(38, "C'est toi la batéries!", DEFAULT, "Nous transportons 10000 milliards de bactéries. Déjà c’est ouf. Et en plus, on a 1000 espèces différentes, ce qui représente 1 kg. Si tu veux perdre du poids, lave toi bien comme il faut. Mais quand même, 1 kilogramme de bactéries sur nous et en nous, c’est chauuuuud.", DEFAULT, 'https://www.topito.com/top-anecdote-scientifique-bac-s', DEFAULT, DEFAULT, 1, 8, DEFAULT, DEFAULT),
(39, "Il n'y a pas si longtemps, personne ne voyait le bleu", DEFAULT, "Dans L’Odyssée de Homère, la mer était décrite « couleur de vin » et non pas bleu ou vert. À cette époque, le mot bleu n’existait pas. Le noir et le blanc sont apparus en premier, puis le rouge, le jaune et le vert. Le bleu devint couleur au 9ème siècle. En fait, on ne voit pas une couleur s’il n’y a pas de mot pour la décrire. C’est ce qu’un chercheur a conclu après une expérience menée auprès d’une tribu namibienne qui n’avait pas de mot pour le bleu. Ils étaient incapables de distinguer le vert du bleu. C’est fou non ?", DEFAULT, 'https://hitek.fr/42/30-anecdotes-tournage-films-cultes-cinema_8891', DEFAULT, DEFAULT, 1, 9, DEFAULT, DEFAULT),
(41, "le mur de la honte d'inglorious basterds", DEFAULT, "Sur le tournage de son film, Quentin Tarantino refusait à ses acteurs ne serait-ce qu'une minute de répit. À chaque fois que l'un d'entre eux faisait la sieste, il était pris en photo avec un gode violet géant. Ce qui a rapidement dissuadé les membres du casting à fermer les yeux...", DEFAULT, 'https://hitek.fr/42/30-anecdotes-tournage-films-cultes-cinema_8891', DEFAULT, DEFAULT, 1, 9, DEFAULT, DEFAULT),
(42, "les joints dans délire express", DEFAULT, "Le film Délire Express prend pour thématique principale le cannabis. Il a alors fallu rouler de nombreux joints pour le bien de la production. Pour ainsi dire, ce n'est pas moins d'une centaine qui ont dû être préparés par l'équipe de tournage. Enfin, c'est ce qui était prévu à la base...
Étant donné qu'aucun autre membre sur le plateau ne s'avait comment rouler des joints, c'est aux experts, Seth Rogens et Evan Golberg, qu'est revenu la tâche de s'en occuper du début à la fin.", DEFAULT, 'https://hitek.fr/42/30-anecdotes-tournage-films-cultes-cinema_8891', DEFAULT, DEFAULT, 1, 9, DEFAULT, DEFAULT),
(43, "les orteils cassés dans le seigneur des anneaux", DEFAULT, "On ne vous avait pas dit que le métier d'acteur était risqué ? Apparemment, Viggo Mortensen l'a lui aussi appris à ses dépens, dans Le Seigneur des Anneaux. Lors d'une scène du dernier opus de la trilogie, Aragorn donne un énorme coup de pied sur le casque d'un ennemi. La réaction qui en résulte est alors transcendante ! 
Pour cause, Viggo Mortensen s'était en réalité cassé deux orteils suite au choc. Show must go on, comme on dit. La séquence a continué et Peter Jackson a finalement conservé la scène au montage", DEFAULT, 'https://hitek.fr/42/30-anecdotes-tournage-films-cultes-cinema_8891', DEFAULT, DEFAULT, 1, 9, DEFAULT, DEFAULT),
(44, "Dark vador et le test de paternité", DEFAULT, "dark vador ne savait pas qu'il était le père de luke dans star wars. 'Je suis ton père' est devenue l'une des phrases les plus mythiques de l'histoire du cinéma. Dans L'Empire Contre-Attaque, ce passage représente un twist majeur pour les fans de Star Wars. C'est pourquoi George Lucas a tout mis en œuvre pour la maintenir complètement secrète. 
Le script a alors été modifié pour que les acteurs ne soient pas au courant de ce qui se tramait dans l'ombre. Même David Prose, interprète physique de Dark Vador, avait été tenu éloigné de la confidence. C'est au final lors de la post-production que la phrase a été ajoutée, ce qui a permis de maintenir le twist secret jusqu'à sa sortie en salle.", DEFAULT, 'https://hitek.fr/42/30-anecdotes-tournage-films-cultes-cinema_8891', DEFAULT, DEFAULT, 1, 9, DEFAULT, DEFAULT);

COMMIT;

-- -----------------------------------------------------
-- Data for table `anecdote_action`
-- -----------------------------------------------------

INSERT INTO `anecdote_action` (`vote`,`favorite`, `anecdote_id`, `user_id`) VALUES (1, 1, 5, 2),
-- upvote + favorite for User
(1, 0, 8, 2),
(1, 1, 9, 2),(1, 0, 12, 2),
(1, 1, 18, 2),(1, 0, 25, 2),
(1, 1, 31, 2),(1, 0, 32, 2),
-- upvote + favorite for Ameli
(1, 1, 1, 3),(1, 0, 3, 3),
(1, 1, 5, 3),(1, 0, 18, 3),
(1, 1, 22, 3),(1, 0, 31, 3),

-- downVote for User
(2, 0, 1, 2),(2, 0, 6, 2),
(2, 0, 10, 2),(2, 0, 11, 2),
(2, 0, 19, 2),(2, 0, 22, 2),
-- downVote for Ameli
(2, 0, 2, 3),(2, 0, 4, 3),
(2, 0, 6, 3),(2, 0, 19, 3),
(2, 0, 21, 3),(2, 0, 37, 3);

COMMIT;